name: Gitleaks Secret Scan

on:
  push:
    branches:
      - main
      - develop

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v1
        with:
          config: .gitleaks.toml
          report-format: json
          report-path: gitleaks-report.json

      - name: Run Python Script
        run: python3 convert.py

      - name: Upload Gitleaks CSV Report
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-csv-report
          path: gitleaks-report.csv
