name: Gitleaks Scan

on:
  push:
    branches:
      - main
      - '**' # Scan all branches (optional)
  pull_request:
    branches:
      - main

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run Gitleaks
      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          config: .gitleaks.toml  # Optional: Provide custom config if available
          report_format: json    # Export report as JSON
          report_path: gitleaks-report.json
