name: Gitleaks Secret Scan

on:
  push:
    branches:
      - main
      - develop

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Gitleaks
      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.23.1/gitleaks_8.23.1_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks

      # Step 3: Run Gitleaks
      - name: Run Gitleaks
        run: |
          gitleaks detect --source=. --report-format=json --report-path=gitleaks-report.json || true

      # Step 4: Convert JSON to CSV
      - name: Convert Gitleaks JSON to CSV
        run: |
          python3 -c "
import json
import csv

input_file = 'gitleaks-report.json'
output_file = 'gitleaks-report.csv'

fields = [
    'Description', 'File', 'StartLine', 'EndLine', 'StartColumn', 'EndColumn',
    'Match', 'Secret', 'Commit', 'Author', 'Email', 'Date', 'Message', 'RuleID',
    'Entropy', 'Fingerprint'
]

with open(input_file, 'r') as json_file:
    data = json.load(json_file)

    with open(output_file, 'w', newline='', encoding='utf-8') as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=fields)
        writer.writeheader()
        for entry in data:
            writer.writerow({field: entry.get(field, '') for field in fields})
          "

      # Step 5: Upload CSV as an Artifact
      - name: Upload Gitleaks CSV Report
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-csv-report
          path: gitleaks-report.csv
